const SEED_DATA = [
  {"date":"2025-03-21","food":"Morning shake (TL protein 2 scoops + collagen + fiber + colostrum + 1/4 banana); Trifecta salmon; Aloha bar; Aloha mini; Biena chickpeas 2 tbsp; coconut water 16oz; cortado; chicken breast dinner salad + duck-fat fries; NFGY 196g; 2 Godiva dark chocolates","exercise":"Yoga 60 min; Tonal 26:34 rows/back (8,081 lbs); sauna 15 min","weight":null,"sleep_hours":null,"sleep_quality":null,"hrv":null,"rhr":null,"mood":null,"energy":null,"notes":"~2,105 kcal | P 245g | C 137g | F 60g"},
  {"date":"2025-03-22","food":"Morning shake; Aloha bar; NY strip steak; half glass cab; cream of spinach; potato gratin 40g; lamb riblet","exercise":"Tonal 31:44 posterior chain (12,881 lbs) — RDL, goblet squat, split squat PR, calf raise; yoga 60 min","weight":null,"sleep_hours":6.73,"sleep_quality":"good","hrv":105,"rhr":53,"mood":null,"energy":null,"notes":"Sleep score 84. ~1,990 kcal | P 211g"},
  {"date":"2025-03-23","food":"Morning shake; ham & cheese croissant 85g; 2 cortados; Aloha bar; Trifecta kung pao shrimp; Bahn Mi grilled chicken thigh salad double chicken","exercise":"Tonal 36:55 upper body PRs (9,642 lbs) — bench press, barbell front raise, half-kneeling press, incline fly; Ashtanga 60 min; 25 pushups; sauna 15 min; Peloton 15 min","weight":null,"sleep_hours":5.65,"sleep_quality":"fair","hrv":122,"rhr":48,"mood":null,"energy":null,"notes":"Sleep score 73. DST spring forward. ~1,805 kcal | P 199g"},
  {"date":"2025-03-24","food":"Cortado; morning shake; Aloha bar; NFGY 167g; Norse code 2 scoops; mussels drained 69g; clams; cottage cheese 150g low fat","exercise":"Tonal upper back (10,432 lbs) — lat pulldown, straight arm pulldown; Tonal session 2 (5,200 lbs); yoga 45 min; Peloton 30 min Z2; pull-ups 20; sauna 15 min","weight":null,"sleep_hours":5.23,"sleep_quality":"fair","hrv":109,"rhr":45,"mood":null,"energy":null,"notes":"Sleep score 80. Leg cramp — electrolyte depletion. ~2,267 kcal | P 220g"},
  {"date":"2025-03-25","food":"Cortado; morning shake; Aloha bar; Trifecta dijon pork; Fish Sausalito: half crab roll, 15 fries, Scrimshaw pilsner 6oz; NFGY 196g; 2 Godiva dark chocolates","exercise":"Peloton 15 min; yoga 60 min; 100 pushups; Tonal Ultimate Back (11,636 lbs) — seated lat pulldown, straight arm pulldown, X-pulldown","weight":null,"sleep_hours":6.43,"sleep_quality":"great","hrv":183,"rhr":43,"mood":null,"energy":"high","notes":"Sleep score 89. HRV 183 peak recovery. ~1,590 kcal | P 168g. Deficit ~1,160 kcal."},
  {"date":"2025-03-26","food":"Cortado; morning shake; Aloha bar; Trifecta Korean glazed chicken; mussels drained; NFGY 167g; clams drained","exercise":"Yoga 60 min; Tonal session 1 (7,983 lbs) — bent-over rows, face pulls, Y-pulls; Peloton 30 min Z2; Tonal session 2 (5,200 lbs); pull-ups 20; sauna 15 min","weight":null,"sleep_hours":4.75,"sleep_quality":"poor","hrv":125,"rhr":47,"mood":null,"energy":null,"notes":"Sleep score 72. Worked late ~1am. ~1,815 kcal | P 243g"},
  {"date":"2025-03-27","food":"Morning shake; Aloha bar; Trifecta sweet garlic pork; Perbacco SF business dinner: olives, arancini, veal carpaccio, fennel salad, halibut, clams, shrimp","exercise":"Tonal leg (8,008 lbs) — RDL PR, rack squat, goblet curtsy lunge; pull-ups 5; sauna 15 min; 8,000 airport steps","weight":null,"sleep_hours":6.83,"sleep_quality":"great","hrv":154,"rhr":44,"mood":null,"energy":null,"notes":"Sleep score 89. Late flight to Denver. ~1,590 kcal | P 170g"},
  {"date":"2025-03-28","food":"Norse code 2 scoops; egg white bites x2; cottage cheese; Boar's Head turkey 10 slices; chips 1 cup; PB M&Ms mega handful; dirty gin martini; BK Whopper + 10 fries + 3 nuggets","exercise":"6,300 steps (Denver hotel — no gym, travel day)","weight":null,"sleep_hours":9.0,"sleep_quality":"good","hrv":null,"rhr":null,"mood":null,"energy":null,"notes":"Denver hotel. No Eight Sleep. Birthday party + Burger King. ~2,230 kcal"},
  {"date":"2025-03-29","food":"Flat white; morning shake; Aloha bar; Chick-fil-A 12 grilled nuggets; Trifecta Korean chicken; roasted beets 140g; mussels 69g; Norse code 2 scoops","exercise":"Tonal biceps 9:50 (1,965 lbs) — seated bicep curl PR; pull-ups 15; yoga 60 min; pool swimming 7 min; pushups 50","weight":null,"sleep_hours":5.23,"sleep_quality":"fair","hrv":109,"rhr":45,"mood":null,"energy":null,"notes":"Sleep score 80. Pool party. ~1,310 kcal | P 203g"},
  {"date":"2025-03-30","food":"Morning shake; Norse code 2 scoops; Trifecta beef cheddar chili; PB M&Ms 6; Aloha bar; tuna belly sashimi; homemade miso soup 1.5 cups; NFGY 220g","exercise":"Tonal full body (13,859 lbs) — barbell deadlift, bicep curls, single-leg RDL, Pallof press PRs; yoga 60 min; Peloton 15 min Z2; pull-ups 15; pushups 100; massage 60 min","weight":null,"sleep_hours":6.8,"sleep_quality":"good","hrv":140,"rhr":45,"mood":null,"energy":null,"notes":"Sleep score 87. Pallof press PR. ~1,805 kcal"},
  {"date":"2025-03-31","food":"Morning shake; Aloha mini; Norse code 3 scoops; mussels drained; clams; Trifecta maple dijon chicken; roasted beets 70g; LesserEvil popcorn 1 bag; homemade beef stew 1 large bowl","exercise":"Peloton 30 min Z1; yoga 45 min; Tonal upper back (10,432 lbs); pull-ups 10; deep tissue massage 90 min; sauna 15 min","weight":null,"sleep_hours":6.72,"sleep_quality":"good","hrv":150,"rhr":40,"mood":null,"energy":null,"notes":"Sleep score 85. HRV 150. Homemade beef stew. ~2,267 kcal"},
  {"date":"2025-04-01","food":"Flat white; morning shake; Aloha mini; Norse code 2 scoops; Trifecta Mediterranean chicken; raw oysters 6; Fish Sausalito: black cod + crab from son's leftover; NFGY 185g","exercise":"Stretching 30 min; Jivamukti yoga 60 min; heated vinyasa 60 min (84\u00b0F); Tonal core (2,112 lbs) — standing lift PR; Tonal lower body (9,158 lbs) — goblet squat, front squat PR, reverse lunge, nordics; sauna 15 min","weight":null,"sleep_hours":6.1,"sleep_quality":"great","hrv":183,"rhr":43,"mood":null,"energy":"high","notes":"Sleep score 89. HRV 183 peak. Double yoga + double Tonal. Front squat PR. ~1,730 kcal | P 242g"},
  {"date":"2025-04-02","food":"Flat white; morning shake; Norse code 2 scoops fasted; Aloha bar; coconut water 8oz; turkey wrap; roasted chicken 93g; roasted beets 54g; dinner: chicken breast + rice + mushrooms + 2 eggs","exercise":"Tonal upper fasted AM (9,093 lbs \u2014 OH press, bicep curls, tricep ext, lat pulldown, bench press); yoga vinyasa 60 min; Peloton 30 min Z2; pull-ups 10","weight":null,"sleep_hours":5.9,"sleep_quality":"poor","hrv":100,"rhr":50,"mood":null,"energy":null,"notes":"Sleep score 77. Worked late ~1am. First ever fasted AM Tonal. HRV dropped to 100."},
  {"date":"2025-04-03","food":null,"exercise":"Tonal: 35:52, 10,409 lbs, 115 kcal, 29.3 kJ, TUT 9:05. Block 1: Half Kneeling Single Arm Pull (warm-up, 1,230 lbs \u2014 25\u00d716, 42\u00d716), Standing Face Pull (warm-up, POWER PR, 789 lbs \u2014 39\u00d78, 60\u00d78). Block 2: Barbell Seated Lat Pulldown (STRENGTH PR 98 lbs, 4,986 lbs \u2014 5 sets: 87/92/98/104/111 lbs). Block 3: Single Arm Bent Over Row (1,380 lbs \u2014 25\u00d716, 25\u00d716, 23\u00d720), Seated Biceps Curl (STRENGTH PR 25 lbs, 1,404 lbs \u2014 25\u00d710, 20\u00d710, 21\u00d712). Block 4 circuit \u00d73: Single Arm Squat w/ Row (620 lbs), Alternating Staggered Push-up, Rotational Chop, Skater Bound.","weight":null,"sleep_hours":null,"sleep_quality":null,"hrv":null,"rhr":null,"mood":null,"energy":null,"notes":null}
];
